### ISSUE TITLE
Add text about GMS services may require high availability

### ISSUE THREAD

**Issue by brianmajor** [ivoa-std/GMS#13]
As raised by Adrian on the RFC page, a note should be added stating that GMS availability is important because it is often in the path of many services with proprietary information.

**Comment by brianmajor** [comment]
This is somewhat related to Markus' comment about the need to cache registry lookups.

**Comment by cbanek** [comment]
If you're going to cache the response of a group membership query, then the service should probably mention when that caching should expire or when the cache should be refreshed.  This way people can be removed from groups safely.
