### ISSUE TITLE
Recommendations and support for caching

### ISSUE THREAD

**Issue by brianmajor** [ivoa-std/GMS#14]
During the GMS RFC review session at the interop It was suggested that:

1. The specification should clearly state that clients of GMS should consider caching the mapping of resource identifiers to access URLs.  The purpose of this is to avoid using RegTAP in a high transactional service.  This is mostly there in the specification now after @msdemlei first raised the issue on the RFC page.
2. The specification should clearly state that clients of GMS should consider caching users' group membership information.  The purpose of this is to allow clients to respond to requests when the target GMS service is temporarily unavailable.
3. GMS services could provide extra information on each call that would give clients an idea of long the membership results should be considered valid.  This could be achieved by returning one or two timestamps, such as `expiresAt`.  Clients could use this information to determine when their membership cache for a given user needs to be refreshed.

The current response from a call to /<gms-service>/search is in simple plain/text format with the list of group names representing the user's memberships.  So, there isn't currently a place in the response body to convey timestamps.

However, the HTTP response header `Expires` might be the best fit.  (See section 14.21 here:  https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html).  It essentially would convey the date when the group membership information should no longer be considered accurate.

**Comment by cbanek** [comment]
Yeah I like the expires way of doing it, that also means that you could use other http proxy caching I think too that will keep track of that for you as well.

**Comment by brianmajor** [comment]
Ok.  Do you think we should recommend setting `Expires` or just recommend using the general HTTP caching mechanisms?

**Comment by cbanek** [comment]
I think it's both, using Expires should let HTTP caching mechanisms know how long we want it to last.  Maybe suggest a default expires header?  I think Expires = 0 will also prevent caching for those who want that.

**Comment by Zarquan** [comment]
+1 for using the Expires header
